name: Run tests in container
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Run tests with Docker Compose
      run: |
        docker compose -f docker-compose.yaml up --build -d
        docker compose -f docker-compose.yaml exec -T app pytest --cov=./ --cov-report=xml -vv -ss
      env:
        POSTGRES_USER: "test"
        POSTGRES_PASSWORD: "test"
        POSTGRES_DB: "workout"
        POSTGRES_HOST: "test-db"
        POSTGRES_PORT: 5432
        FIRST_SUPERUSER_USERNAME: "testuser"
        FIRST_SUPERUSER_EMAIL: "testuser@mail.com"
        FIRST_SUPERUSER_PASSWORD: "password"
        ENV: "test"
    
    - name: Cleanup
      if: always()
      run: docker compose -f docker-compose.yaml down --volumes
